[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
DocStringExtensions = "0.9"
Documenter = "1"
